### ISSUE TITLE
ACTPCD Embeddings

### ISSUE THREAD

**Issue by NigelNelson** [HaoyiZhu/PointCloudMatters#2]
Hello, first of all thank you for your amazing work and sharing a well structured and documented repo.

I have a question regarding the coordinate embedding implementation for the ACTPCD model:
In `forward_pcb_embed` [here](https://github.com/HaoyiZhu/PointCloudMatters/blob/8ec0b88454b0db07f994bd2b877d08cf5ec8f94e/src/models/components/act/act.py#L540)
There is the following code:
```python
        pcd_pos = self.coord_embedding_sine(coord[: offset[0]])
        features = rearrange(
            features,
            "(b n) c -> b c 1 n",
            n=self.pcd_npoints,
        )
        pcd_pos = repeat(
            pcd_pos,
            "n c -> b c 1 n",
            b=features.shape[0],
        )
        return features, pcd_pos
```
Based on the indexing of the coordinates and the use of the repeat function call on the output `pcd_pos`, is the intention here to compute the coordinate embedding for the first point cloud in a batch, then use that embedding for the rest of the batch? If that is the case, won't that lead to significant loss of performance for all point clouds in the batch besides index 0?

**Comment by HaoyiZhu** [comment]
You are right! Sorry for that.

I used to apply fixed positional embedding based on sampled points' orders, so I just repeated it over batches. Then I realized that applying positional embedding based on coordinates may be a better choice, but I forgot to change the following codes.

Thank you for pointing this out!
