### ISSUE TITLE
Questions about adding more envs

### ISSUE THREAD

**Issue by Lyy-iiis** [HaoyiZhu/PointCloudMatters#4]
Hello, I try to add more tasks on Maniskill2 to your env. However, in Maniskill2 repo, I can't find any version that matches your code, can you provide the way that you get your env code. Thanks!

**Comment by HaoyiZhu** [comment]
Hi, thanks for your question! When we started this project, ManiSkill2 was at version 0.5.3. You can find their source code at [this branch](https://github.com/haosulab/ManiSkill/tree/v0.5.3).

**Comment by Lyy-iiis** [comment]
I find version 0.5.3, but it seems your env code is not totally identical to the repo. Do you make some minor change to adapt your experiment (one thing I find is that set random seed) ?

**Comment by HaoyiZhu** [comment]
Yes. We made some minor modifications to satisfy our evaluation experiments, but I think it's also okay to use the original environments.

**Comment by Lyy-iiis** [comment]
Ok, thank you!
